### ISSUE TITLE
Issue with Bartender4

### ISSUE THREAD

**Issue by sassouiabd** [jwldnr/jButtonFlash#1]
Does not work with Bartender4 for some reasons

**Comment by woldner** [comment]
I'm first now addressing this issue since I've seen an increase in requests relating to the Bartender AddOn. 

This is definitely something that I would like to do, but I've not been able to fit this into my daily life. I would gladly accept an PR that fixes this issue, but in absence of such a PR, I'd have to ask you to wait until I've got time to fix this in my spare time.. 

Thanks for your understanding

**Comment by Bodify** [comment]
I'm no coder but with the tiniest amount of insight and being extremely stubborn, ChatGPT and I managed to cook up a version that works with Bartender4. I have not bothered attempting to make it work with the default actionbars simultaneously. Feel free to contact me if you want to peek the code and clean it up to make a more "proper" version for actual release. @bodify on discord

**Comment by woldner** [comment]
Upcoming release 2.0 will include Bartender4 support. Thanks to @Bodify for supplying a working example 🤗
